layer.conf: Fix openamp-layer dependency
meta-xilinx-standalone-experimental failes to parse with below errors

ERROR: No recipes in default available for:
  /scratch/sandeep/yocto/2024.1/yp-bc/sources/poky/../meta-xilinx/meta-xilinx-standalone-experimental/recipes-openamp/libmetal/libmetal-xlnx_%.bbappend
  /scratch/sandeep/yocto/2024.1/yp-bc/sources/poky/../meta-xilinx/meta-xilinx-standalone-experimental/recipes-openamp/open-amp/open-amp-xlnx_%.bbappend

Hence add openamp-layer dependency to LAYERDEPENDS variable.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>