python3-dtc_1.5.1.bb: Explicitly set the path to run make during configure
With current recipe,during build it fails with the following error:
xecuting Tasks
ERROR: python3-dtc-native-1.5.1-r0 do_configure: Execution of 'x86_64-linux/python3-dtc-native/1.5.1-r0/temp/run.do_configure.26600' failed with exit code 1:
make: *** No rule to make target 'version_gen.h'.  Stop.
WARNING: x86_64-linux/python3-dtc-native/1.5.1-r0/temp/run.do_configure.26600:1 exit 1 from 'do_configure'

ERROR: Logfile of failure stored in: x86_64-linux/python3-dtc-native/1.5.1-r0/temp/log.do_configure.26600

Explicitly set the path to change directory into so that the make command is succesful.

Signed-off-by: Sai Hari Chandana Kalluri <chandana.kalluri@xilinx.com>