qemu-xilinx-system-native: Fix license check when empty LICENSE_FLAGS_ACCEPTED
Fix an issue that results in:

 Traceback (most recent call last):
  File "Var <DEPENDS>", line 1, in <module>
  bb.data_smart.ExpansionError: Failure expanding variable DEPENDS, expression was pkgconfig-native  glib-2.0-native zlib-native ninja-native meson-native pixman-native qemu-xilinx-native bison-native ninja-native meson-native qemu-xilinx-multiarch-helper-native${@' pmu-rom-native' if 'xilinx' in d.getVar('LICENSE_FLAGS_ACCEPTED').split() else ''} alsa-lib-native dtc-native libgcrypt-native libslirp-native which triggered exception AttributeError: 'NoneType' object has no attribute 'split'
  The variable dependency chain for the failure is: DEPENDS

This only occurs if no LICENSE_FLAGS_ACCEPTED is defined.  This should not be
a blocking error.  Instead the user is warned of reduced functionality and we
continue the build.

Signed-off-by: Mark Hatle <mark.hatle@amd.com>
(cherry picked from commit fe4b15d97e0b5ce73cd3186ac3e380df07c9d1ca)
Signed-off-by: Mark Hatle <mark.hatle@amd.com>