Revert "kernel-module-zocl: Rename from zocl"
This reverts commit 60542eb1dea413c631330524836412cfefc933bb.

This also makes the same change to 2024.1 version.

This change caused:

ERROR: core-image-minimal-1.0-r0 do_rootfs: Unable to find package with name 'kernel-module-zocl' in SPDX file .../tmp/deploy/spdx/by-hash/zynqmp_generic/sstate:kernel-module-zocl:zynqmp_generic-poky-linux:202410.2.17.0:r0:zynqmp_generic:12:/kernel-module-zocl-6.6.10-xilinx-g3af4295e00ef.spdx.json

Signed-off-by: Mark Hatle <mark.hatle@amd.com>