zocl_git.bb: Update the S path for zocl
xrt repo has restructuring causing License of the zocl to break.
ERROR: zocl-2.2.0+gitAUTOINC+f91777f3b8-r0 do_populate_lic: QA Issue:
zocl: LIC_FILES_CHKSUM points to an invalid file:

Update the S path for zocl to fix this issue

Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>