Revert "Updated SRCREV for 2023.1_2659"
This reverts commit c043692501039e8521c4da64de166232aa0728cf.

Failed with:
  git/drivers/pinctrl/pinctrl-zynqmp.c:163:27: error: 'PM_PINCTRL_PARAM_SET_VERSION' undeclared (first use in this function)
                 if (ret < PM_PINCTRL_PARAM_SET_VERSION)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Mark Hatle <mark.hatle@amd.com>