u-boot_%.bbappend: Fix the breakage on platform init files
Fix the following error for machines like microzed:
ERROR: Nothing PROVIDES 'virtual/xilinx-platform-init'

This happens because the contrib recipe is overriding the
HAS_PLATFORM_INIT instead of appending the configuration for minized
machine. This patch fixes the issue by adding an append.

Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>