xlnx-embeddedsw.bbclass: Fix broken recipe parse
Commit 1243552796558a00b4f0d7ed9c9c3d41d7031a7a ("xlnx-embeddedsw:
Cleanup and remove old versions, no longer supported") removed also
'git' varFlag lines which causes following parsing error with _git.bb
recipes that inherit this bbclass:

  ERROR: ExpansionError during parsing .../poky/meta-xilinx/meta-xilinx-standalone/recipes-bsp/embeddedsw/pmu-firmware_git.bb
  Traceback (most recent call last):
    File ".../poky/bitbake/lib/bb/fetch2/git.py", line 250, in Git.urldata_init(ud=<bb.fetch2.FetchData object at 0x7fc5db2b5610>, d=<bb.data_smart.DataSmart object at 0x7fc5de3e5310>):

      >        ud.setup_revisions(d)

    File ".../poky/bitbake/lib/bb/fetch2/__init__.py", line 1349, in FetchData.setup_revisions(d=<bb.data_smart.DataSmart object at 0x7fc5de3e5310>):
               for name in self.names:
      >            self.revisions[name] = srcrev_internal_helper(self, d, name)

    File ".../poky/bitbake/lib/bb/fetch2/__init__.py", line 1214, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7fc5db2b5610>, d=<bb.data_smart.DataSmart object at 0x7fc5de3e5310>, name='default'):
             if srcrev == "AUTOINC":
      >          srcrev = ud.method.latest_revision(ud, d, name)

    File ".../poky/bitbake/lib/bb/fetch2/__init__.py", line 1626, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7fc5db2b5610>, d=<bb.data_smart.DataSmart object at 0x7fc5de3e5310>, name='default'):
               except KeyError:
      >            revs[key] = rev = self._latest_revision(ud, d, name)
                   return rev
    File ".../poky/bitbake/lib/bb/fetch2/git.py", line 757, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7fc5db2b5610>, d=<bb.data_smart.DataSmart object at 0x7fc5de3e5310>, name='default'):
                           return sha1
      >        raise bb.fetch2.FetchError("Unable to resolve '%s' in upstream git repository in git ls-remote output for %s" % \
                   (ud.unresolvedrev[name], ud.host+ud.path))
  bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Unable to resolve 'git' in upstream git repository in git ls-remote output for github.com/Xilinx/embeddedsw.git
  The variable dependency chain for the failure is: SRCPV -> PV -> WORKDIR -> T

  ERROR: Parsing halted due to errors, see error messages above

Restore those lines as they were before the commit that removed them
to be able to use this layer.

Signed-off-by: Niko Mauno <niko.mauno@vaisala.com>