xen-tools_4.21: Drop redundant libxenmanage workaround
xen-tools.inc (meta-virtualization) now declares the libxenmanage /
libxenmanage-dev PACKAGES, FILES and staticdev entries natively
(libxenmanage was added in Xen 4.21+, see meta-virtualization commit
2734c371 'xen-tools: allow empty libxenmanage package for pre-4.21').

The local Xilinx workaround block duplicating those same
PACKAGES/RDEPENDS/FILES declarations is therefore obsolete and now
causes a do_package QA fatal error:

  ERROR: xen-tools-4.21+stable-xilinx+git-r0 do_package: QA Issue:
  xen-tools-libxenmanage is listed in PACKAGES multiple times
  xen-tools-libxenmanage-dev is listed in PACKAGES multiple times

Remove the redundant block; the base recipe's declarations are
sufficient.

AI-Generated: GitHub Copilot (Claude Sonnet 5)

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20260721194244.2239644-14-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>