u-boot-tools-xlnx: add missing dependencies
The issue can be reproduced with:
$ bitbake u-boot-tools-xlnx -c compile -f --skip-setscene

The swig is needed on the native sysroot:
| error: command 'swig' failed: No such file or directory

The util-linux-libuuid is needed on target sysroot:
| .../1_v2023.01-xilinx-v2023.1+gitAUTOINC+0c2f5b2994-r0/git/tools/mkeficapsule.c:18:10: fatal error: 'uuid/uuid.h' file not found

The gnutls is needed on target sysroot:
| .../1_v2023.01-xilinx-v2023.1+gitAUTOINC+0c2f5b2994-r0/git/tools/mkeficapsule.c:21:10: fatal error: 'gnutls/gnutls.h' file not found

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>