meta-xilinx-core: Move lmsensors bbappend to dynamic layer
lmsensors is provided by meta-oe, so the bbappend fails with:

  ERROR: No recipes in default available for:
    .../meta-xilinx/meta-xilinx-core/recipes-bsp/lm_sensors/lmsensors_%.bbappend

when meta-oe is not part of the project.

Signed-off-by: Mark Hatle <mark.hatle@amd.com>