lwip_2024.1: Update lwip version to 2.2.0
lwip-echo-server baremetal application fails to build with below
errors:

ERROR: mc:cortexr5-0-zynqmp-baremetal:lwip-2024.1+gitAUTOINC+2a07bc9c76-r0 do_configure: ExecutionError('/scratch/sandeep/yocto/2024.1/yp-dev/build-sdt/tmp-cortexr5-0-zynqmp-baremetal/work/cortexr5-vfpv3d16-xilinx-eabi/lwip/2024.1+gitAUTOINC+2a07bc9c76-r0/temp/run.do_configure.2679569', 1, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2024.1/yp-dev/build-sdt/tmp-cortexr5-0-zynqmp-baremetal/work/cortexr5-vfpv3d16-xilinx-eabi/lwip/2024.1+gitAUTOINC+2a07bc9c76-r0/temp/log.do_configure.2679569
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/meta-xilinx/meta-xilinx-standalone-experimental/recipes-libraries/libxil_2024.1.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/../meta-xilinx/meta-xilinx-core/recipes-bsp/device-tree/device-tree.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-core/newlib/libgloss_4.2.0.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-core/newlib/newlib_4.2.0.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/cmake/cmake-native_3.24.2.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/gcc/gcc-cross_12.2.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/gcc/gcc-runtime_12.2.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/gcc/libgcc_12.2.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:virtual:native:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/../meta-virtualization/recipes-kernel/dtc/python3-dtc_1.6.1.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:virtual:native:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/../meta-virtualization/recipes-kernel/lopper/lopper_git.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:virtual:native:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/ninja/ninja_1.11.1.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:virtual:native:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:virtual:native:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:virtual:native:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:virtual:native:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/python/python3-pyyaml_6.0.bb:do_populate_sysroot', 'mc:cortexr5-0-zynqmp-baremetal:virtual:native:/scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/meta/recipes-devtools/python/python3_3.10.6.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['libxil', 'device-tree', 'libgloss', 'newlib', 'cmake-native', 'gcc-cross-arm', 'gcc-runtime', 'libgcc', 'quilt-native', 'python3-dtc-native', 'lopper-native', 'ninja-native', 'patch-native', 'pkgconfig-native', 'pseudo-native', 'python3-pyyaml-native', 'python3-native', 'libtool-native', 'attr-native', 'bzip2-native', 'libtirpc-native', 'sqlite3-native', 'readline-native', 'zlib-native', 'libffi-native', 'libnsl2-native', 'xz-native', 'ncurses-native', 'util-linux-libuuid-native', 'gdbm-native', 'openssl-native', 'canps', 'qspipsu', 'xilstandalone', 'dppsu', 'gpiops', 'iicps', 'intc', 'pciepsu', 'rtcpsu', 'video-common', 'zdma', 'coresightps-dcc', 'csudma', 'resetps', 'sysmonpsu', 'dpdma', 'common', 'sdps', 'emacps', 'scugic', 'uartps', 'ddrcpsu', 'clockps', 'avbuf', 'usbpsu', 'ttcps', 'axipmon', 'ipipsu', 'wdtps', 're2c-native', 'zstd-native', 'curl-native', 'flex-native', 'binutils-cross-arm', 'gmp-native', 'libmpc-native', 'texinfo-dummy-native', 'mpfr-native', 'gnu-config-native', 'python3-installer-native', 'python3-wheel-native', 'python3-picobuild-native', 'python3-humanfriendly-native', 'python3-anytree-native', 'python3-setuptools-native', 'python3-six-native', 'python3-ruamel-yaml-native', 'python3-cython-native', 'libyaml-native', 'dtc-native', 'python3-setuptools-scm-native', 'swig-native', 'gettext-minimal-native', 'perl-native', 'm4-native', 'python3-flit-core-native', 'python3-pyparsing-native', 'python3-tomli-native', 'python3-packaging-native', 'python3-typing-extensions-native', 'python3-pip-native', 'libpcre-native', 'make-native', 'unzip-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| lwip213 Driver doesn't have yaml file
| install: target '/scratch/sandeep/yocto/2024.1/yp-dev/build-sdt/tmp-cortexr5-0-zynqmp-baremetal/work/cortexr5-vfpv3d16-xilinx-eabi/lwip/2024.1+gitAUTOINC+2a07bc9c76-r0/git//ThirdParty/sw_services/lwip213/src//' is not a directory: No such file or directory
| WARNING: /scratch/sandeep/yocto/2024.1/yp-dev/build-sdt/tmp-cortexr5-0-zynqmp-baremetal/work/cortexr5-vfpv3d16-xilinx-eabi/lwip/2024.1+gitAUTOINC+2a07bc9c76-r0/temp/run.do_configure.2679569:146 exit 1 from 'do_configure'
| WARNING: Backtrace (BB generated script):
| 	#1: do_configure, /scratch/sandeep/yocto/2024.1/yp-dev/build-sdt/tmp-cortexr5-0-zynqmp-baremetal/work/cortexr5-vfpv3d16-xilinx-eabi/lwip/2024.1+gitAUTOINC+2a07bc9c76-r0/temp/run.do_configure.2679569, line 146
| 	#2: main, /scratch/sandeep/yocto/2024.1/yp-dev/build-sdt/tmp-cortexr5-0-zynqmp-baremetal/work/cortexr5-vfpv3d16-xilinx-eabi/lwip/2024.1+gitAUTOINC+2a07bc9c76-r0/temp/run.do_configure.2679569, line 216
ERROR: Task (mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/meta-xilinx/meta-xilinx-standalone-experimental/recipes-libraries/lwip_2024.1.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1246 tasks of which 1244 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  mc:cortexr5-0-zynqmp-baremetal:/scratch/sandeep/yocto/2024.1/yp-dev/sources/meta-xilinx/meta-xilinx-standalone-experimental/recipes-libraries/lwip_2024.1.bb:do_configure
Summary: There were 26 WARNING messages.
Summary: There was 1 ERROR message, returning a non-zero exit code.

This is due to lwip version has upgraded from 2.1.3 to 2.2.0 in esw
repo, so update lwip version.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>