meta-xilinx-standalone: Add binutils workaround
Workaround for:

    ERROR: binutils-cross-canadian-aarch64-2.39-r0 do_package_qa: QA Issue: non -staticdev package contains static .a library: binutils-cross-canadian-aarch64 path '/usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-oesdk-linux/usr/lib/aarch64-xilinx-elf/bfd-plugins/libdep.a' [staticdev]

Need for the workaround was introduced with latest version of poky (langdale)

Signed-off-by: Mark Hatle <mark.hatle@amd.com>