initramdisk-xilinx: Fix name
The ramdisk does not have 'rootfs' in the name, fix this.

  ERROR: initramdisk-petalinux-initramfs-image-1.0-r0 do_install: Unable to find expected initramfs: petalinux-initramfs-image-vck-sc-zynqmp.rootfs.cpio.gz.u-boot

See:
  https://git.yoctoproject.org/poky/commit/meta/classes-recipe/image-artifact-names.bbclass?id=6f6c79029bc2020907295858449c725952d560a1

Signed-off-by: Mark Hatle <mark.hatle@amd.com>