xrt_git.bb: Replace deprecated boost macros
xrt source includes boost/detail/endian.hpp to detect endianess.  In Yocto,
gatesgarth, boost version is 1.74 which has deprecated some older macros
resulting in the below error

 /workspaces/ckalluri/yocto/master-dev/builds-versal/tmp/work/cortexa72-cortexa53-xilinx-linux/xrt/202010.2.7.0-r0/git/src/runtime_src/xocl/core/kernel.cpp:24:10:
fatal error: boost/detail/e ndian.hpp: No such file or directory |    24 |
| compilation terminated.

To fix the compilation issue, currently include a patch on top of xrt source
that replaces the deprecated BOOST_BYTE_ORDER macro with __BYTE_ORDER macro to
detect endianess.

Signed-off-by: Sai Hari Chandana Kalluri <chandana.kalluri@xilinx.com>