Buildfix due to eglibc -> glibc
Changed all references of eglibc to glibc.
This is required because eglibc was replaced by glibc in poky.

ERROR: ParseError at /media/sdd1/fb/ligh/scm/master-enea/poky/
meta-xilinx/recipes-core/meta/external-xilinx-toolchain.bb:1:
Could not include required file recipes-core/eglibc/eglibc-package.inc

Signed-off-by: Liviu Gheorghisan <liviu.gheorghisan@enea.com>