qemu-xilinx-native: filter --disable-jack option
qemu-xilinx-native does not support jack, thus --disable-jack set by qemu.inc is not supported
and will cause:
 ERROR: unknown option --disable-jack
This will filter this option.