microblaze libxcrypt: Fall back to older style symver support
Using symver related functions results in:

| ../git/lib/crypt-static.c:32:1: error: symver is only supported on ELF platforms
|    32 | SYMVER_crypt;
|       | ^~~~~~~~~~~~

Microblaze does not support these functions at this time, so fall back
to the older approach to resolve this issue.

Signed-off-by: Mark Hatle <mark.hatle@xilinx.com>