kc705-microblazeel.conf: Add UBOOT_MACHINE to kc705
Due to changes in 1138c5623d3e0c415d18b109ccf6c4f301c173f6, the
definiton of UBOOT_MACHINE was removed. This causes the following error

ERROR: Nothing PROVIDES 'virtual/bootloader'
u-boot-xlnx PROVIDES virtual/bootloader but was skipped: Either
UBOOT_MACHINE or UBOOT_CONFIG must be set in the kc705-microblazeel
machine configuration.
u-boot PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE
or UBOOT_CONFIG must be set in the kc705-microblazeel machine
configuration.
u-boot-xlnx-dev PROVIDES virtual/bootloader but was skipped: Either
UBOOT_MACHINE or UBOOT_CONFIG must be set in the kc705-microblazeel
machine configuration.

This is a requried setting, set it to microblaze-generic_config

Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>