xlnx-embeddedsw: Define a floating git version
While the 'git' version should never be preferred, some may find it useful
for development.  However, this was causing a parse error in some
configurations:

  fsbl-firmware_git.bb: Exception during build_dependencies for T

  bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression
  was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError:
  Fetcher failure: Unable to resolve 'git' in upstream git repository in git
  ls-remote output for github.com/Xilinx/embeddedsw.git

  The variable dependency chain for the failure is:
    SRCPV -> PV -> WORKDIR -> T

Signed-off-by: Mark Hatle <mark.hatle@amd.com>