Revert "Updated SRCREV for 2022"
This reverts commit a1643135ff0942233bd475b1319e53d75c68defa.

Caused QEMU build failure.

When building for mingw32:

| ../git/hw/misc/xlnx-versal-cframe-reg.c: In function 'cframe_incr_far':
| ../git/hw/misc/xlnx-versal-cframe-reg.c:385:18: error: expected identifier or '(' before '=' token
|   385 |     uint32_t far = ARRAY_FIELD_EX32(s->regs, FAR0, FRAME_ADDR);
|       |                  ^
| ../git/hw/misc/xlnx-versal-cframe-reg.c:390:10: error: expected expression before ';' token
|   390 |     far++;
|       |          ^
| ../git/hw/misc/xlnx-versal-cframe-reg.c:392:13: error: expected expression before '>' token
|   392 |     if (far > s->cfg.blktype_num_frames[blktype]) {
|       |             ^
| ../git/hw/misc/xlnx-versal-cframe-reg.c:394:13: error: expected expression before '=' token
|   394 |         far = 0;
|       |             ^

Signed-off-by: Mark Hatle <mark.hatle@xilinx.com>