meta-xilinx-core: meta-mingw: Fixes for compilation issues
Various recipes were failing with a meson error similar to:

  ERROR: Executables created by c compiler x86_64-w64-mingw32-gcc --sysroot=.../tmp/work/x86_64-nativesdk-mingw32-w64-mingw32/nativesdk-glib-2.0/2.88.0/recipe-sysroot are not runnable.

This was an issue where meson properly detected cross-compilation, but
the default value EXEWRAPPER_ENABLED was set to true, but no mingw
emulation was present.

Additionally libgpg-error was enabling -P unconditionally in
CPPFLAGS.  This triggered the following error:

  x86_64-w64-mingw32-windres: invalid option -- 'P'

Signed-off-by: Mark Hatle <mark.hatle@amd.com>
Message-ID: <20260630170422.1426595-2-mark.hatle@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>