xrt, zocl: Update commit id
Changelog:
   CR-1142089 - Improvements to AIE graph hierarchy and channel support (#7656)
   Add support for LSP for use by emacs/eglot (#7665)
   driver plug-in should support non-DRM based device node (#7664)
   CR-1170456 Add NOT SUPPORTED string to all ps tests (#7663)
   EDGEML-5898 Search windows PATH for xbutil directory to find loader (#7662)
   Force xclbin won't impact if current xclbin in use (#7658)
   moving to latest petalinux (#7661)
   Vitis-8819 Elf parsing and patching (#7659)
   add all reports to a sub-folder (#7651)
   VITIS-8853 Refactor SubCmdValidate (#7643)
   Moving to 2023.1 petalinux (#7657)
   Zocl refactoring : Initial version (#7645)
   Providing OS Support for RHEL_8_8 and RHEL_9_2 (#7655)
   Fixing issue with incorrect assumption on system metadata (#7654)
   Align DMA IP driver (#7653)
   fixing edge compilation issue when cloned separately (#7650)
   Move hwctx initializtion of module to xrt::run (#7647)
   Vitis-8819 First-class execution buffer basic elf support (#7644)
   Fixed multislot issues (#7631)
   Changing the mapping of arguments to memory from kernel-based to compute unit based.  Also adding support for host memory. (#7640)
   Templatize internal utility aligned_alloc (#7641)

Signed-off-by: saumya garg <saumya.garg@amd.com>

Add workaround for gitsm failure with this repository.

  git -c gc.autoDetach=false -c core.pager=cat submodule update --recursive --no-fetch failed with exit code 2
  OSError: [Errno 8] Exec format error
  .../xrt/202320.2.16.0-r0/recipe-sysroot-native/usr/bin/../libexec/git-core/git-submodule: 46: .: Can't open /git-sh-i18n

Signed-off-by: Mark Hatle <mark.hatle@amd.com>