meta-microblaze: gdb: Fix target GDB compilation for Linux native
Add patch for Linux native issue

Add library linkage to libatomic to address:

 ld: /usr/include/c++/13.3.0/bits/atomic_base.h:1015:(.text+0x16d0c): undefined reference to `__atomic_compare_exchange_1'

Also remove extra files no longer required.

Signed-off-by: Mark Hatle <mark.hatle@amd.com>