machine-xilinx-overrides.inc: Fix package archs when SOC_VARIANT is null
When SOC_VARIANT is null, bitbake will error out complaining as below

ERROR:  OE-core's config sanity checker detected a potential
misconfiguration. Either fix the cause of this error or at your own
risk disable the checker (see sanity.conf).

Following is the list of potential problems / advisories:

Error, the PACKAGE_ARCHS variable contains duplicates. The
following archs are listed more than once: zynqmp

This patch fixes the above issue and remove duplication of PACKAGE_ARCHS

Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>